REPORT ZASKAB00.
TABLES: BSEG.
TABLES: ANEP.
DATA: BEGIN OF XANEP OCCURS 0.
         INCLUDE STRUCTURE ANEP.
DATA: END   OF XANEP.
DATA: HLP_ANLN1 LIKE   BSEG-ANLN1.
DATA: HLP_ANLN2 LIKE   BSEG-ANLN2.
DATA: HLP_BELNR LIKE   BSEG-BELNR.
DATA: HLP_INDEX LIKE   SYST-INDEX.
DATA: FLG_EOF   VALUE '0'.
DATA: CON_OFF   VALUE '0'.
DATA: CON_ON    VALUE '1'.
FIELD-GROUPS: HEADER, DATEN.
PARAMETERS:     PA_BUKRS LIKE BSEG-BUKRS.
PARAMETERS:     PA_GJAHR LIKE BSEG-GJAHR.
PARAMETERS:     PA_HKONT LIKE BSEG-HKONT.
SELECT-OPTIONS: SO_ANBWA FOR  BSEG-ANBWA.
START-OF-SELECTION.
INSERT BSEG-ANLN1
       BSEG-ANLN2
       BSEG-BELNR
       BSEG-BUZEI INTO HEADER.
WHILE FLG_EOF = CON_OFF.
   CLEAR HLP_INDEX.
   CLEAR HLP_ANLN1.
   CLEAR HLP_ANLN2.
   SELECT * FROM BSEG
      WHERE BUKRS =  PA_BUKRS
        AND GJAHR =  PA_GJAHR
        AND BELNR >  HLP_BELNR
        AND HKONT =  PA_HKONT
        AND KOART =  'A'
        AND ANBWA IN SO_ANBWA.
      IF BSEG-ANBWA(1) CA '23'.
         CHECK BSEG-ANLN1 <> HLP_ANLN1 OR BSEG-ANLN2 <> HLP_ANLN2.
      ENDIF.
      ON CHANGE OF BSEG-BELNR.
         IF HLP_INDEX = 100.
            HLP_BELNR = BSEG-BELNR.
            EXIT.
         ENDIF.
         HLP_INDEX = HLP_INDEX + 1.
      ENDON.
      HLP_ANLN1 = BSEG-ANLN1.
      HLP_ANLN2 = BSEG-ANLN2.
      EXTRACT DATEN.
   ENDSELECT.
   COMMIT WORK.
   IF HLP_INDEX < 100.
      FLG_EOF = CON_ON.
   ENDIF.
ENDWHILE.
SORT.
LOOP.
   AT NEW BSEG-ANLN2.
      SELECT * FROM ANEP INTO TABLE XANEP
         WHERE BUKRS = PA_BUKRS
         AND   GJAHR = PA_GJAHR
         AND   ANLN1 = BSEG-ANLN1
         AND   ANLN2 = BSEG-ANLN2
         AND   AFABE = '01'.
      COMMIT WORK.
   ENDAT.
   LOOP AT XANEP
      WHERE BELNR = BSEG-BELNR
      AND   BUZEI = BSEG-BUZEI.
   ENDLOOP.
   IF SY-SUBRC <> 0.
*                                Start of TR580 changes
*      WRITE:/ 'Line item for the document number:', BSEG-BELNR, 'Line
*               ITEM:', bseg-buzei, 'DOES NOT EXIST'.
      WRITE:/ 'Line item for the document number:', BSEG-BELNR,
              'Line ITEM:', bseg-buzei, 'DOES NOT EXIST'.
*                                End of TR580 changes
   ENDIF.
ENDLOOP.
